<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [2]:
import sys
import re
import os
import time
import random
import json
import yfinance as yf


# def calc_finished_ticker():
#     os.system("awk -F',' '{print $1}' ./inputs/news_reuters.csv | sort | uniq > ./inputs/tickers.txt")


def get_stock_prices():
    fin = open('./inputs/tickers.txt')
    output = './inputs/stockPrices_raw1.json'

    # exit if the output already existed
    if os.path.isfile(output):
        sys.exit("Prices data already existed!")

    price_set = {}
    price_set['^GSPC'] = repeat_download('^GSPC')
    for num, line in enumerate(fin):
        ticker = line.strip()
        print(num, ticker)
        price_set[ticker] = repeat_download(ticker)
        

    with open(output, 'w') as outfile:
        json.dump(price_set, outfile, indent=4)


def repeat_download(ticker, start_date='2013-06-21', end_date='2019-06-21'):
    repeat_times = 2 # repeat download for N times
    for i in range(repeat_times):
        try:
            time.sleep(random.uniform(2, 5))
            price_str = get_price_from_yahoo(ticker, start_date, end_date)
            if price_str: # skip loop if data is not empty
                return price_str
        except Exception as e:
            print(e)
            if i == 0:
                print(ticker, "Http error!")

def get_price_from_yahoo(ticker, start_date, end_date):
    quote = yf.download(ticker, start_date, end_date)
    
    quote.columns = ['open', 'high', 'low', 'close', 'adjClose', 'volume']
    quote.index = quote.index.strftime('%Y-%m-%d')
    
    quote_dict = quote.to_dict()
    
    return quote_dict
    

if __name__ == "__main__":
    get_stock_prices()

[*********************100%***********************]  1 of 1 downloaded
0 ADBE
[*********************100%***********************]  1 of 1 downloaded
1 GOOGL
[*********************100%***********************]  1 of 1 downloaded
2 AMZN
[*********************100%***********************]  1 of 1 downloaded
3 AMGN
[*********************100%***********************]  1 of 1 downloaded
4 AAPL
[*********************100%***********************]  1 of 1 downloaded
5 AVGO
[*********************100%***********************]  1 of 1 downloaded
6 CSCO
[*********************100%***********************]  1 of 1 downloaded
7 CMCSA
[*********************100%***********************]  1 of 1 downloaded
8 COST
[*********************100%***********************]  1 of 1 downloaded
9 FB
[*********************100%***********************]  1 of 1 downloaded
10 INTC
[*********************100%***********************]  1 of 1 downloaded
11 MSFT
[*********************100%***********************]  1 of 1 downloaded
12 NFLX
[*********************100%***********************]  1 of 1 downloaded
13 PYPL
[*********************100%***********************]  1 of 1 downloaded
14 PEP
[*********************100%***********************]  1 of 1 downloaded
15 SBUX
[*********************100%***********************]  1 of 1 downloaded
16 TXN
[*********************100%***********************]  1 of 1 downloaded
17 ABT
[*********************100%***********************]  1 of 1 downloaded
18 ACN
[*********************100%***********************]  1 of 1 downloaded
19 BABA
[*********************100%***********************]  1 of 1 downloaded
20 BUD
[*********************100%***********************]  1 of 1 downloaded
21 T
[*********************100%***********************]  1 of 1 downloaded
22 BAC
[*********************100%***********************]  1 of 1 downloaded
23 BBL
[*********************100%***********************]  1 of 1 downloaded
24 BA
[*********************100%***********************]  1 of 1 downloaded
25 BP
[*********************100%***********************]  1 of 1 downloaded
26 CVX
[*********************100%***********************]  1 of 1 downloaded
27 CHL
[*********************100%***********************]  1 of 1 downloaded
28 C
[*********************100%***********************]  1 of 1 downloaded
29 KO
[*********************100%***********************]  1 of 1 downloaded
30 XOM
[*********************100%***********************]  1 of 1 downloaded
31 FMX
[*********************100%***********************]  1 of 1 downloaded
32 HD
[*********************100%***********************]  1 of 1 downloaded
33 HON
[*********************100%***********************]  1 of 1 downloaded
34 HSBC
[*********************100%***********************]  1 of 1 downloaded
35 IBM
[*********************100%***********************]  1 of 1 downloaded
36 JPM
[*********************100%***********************]  1 of 1 downloaded
37 JNJ
[*********************100%***********************]  1 of 1 downloaded
38 LIN
[*********************100%***********************]  1 of 1 downloaded
39 MA
[*********************100%***********************]  1 of 1 downloaded
40 MCD
[*********************100%***********************]  1 of 1 downloaded
41 MDT
[*********************100%***********************]  1 of 1 downloaded
42 MRK
[*********************100%***********************]  1 of 1 downloaded
43 NKE
[*********************100%***********************]  1 of 1 downloaded
44 NVS
[*********************100%***********************]  1 of 1 downloaded
45 NVO
[*********************100%***********************]  1 of 1 downloaded
46 ORCL
[*********************100%***********************]  1 of 1 downloaded
47 PFE
[*********************100%***********************]  1 of 1 downloaded
48 PM
[*********************100%***********************]  1 of 1 downloaded
49 PG
[*********************100%***********************]  1 of 1 downloaded
50 RY
[*********************100%***********************]  1 of 1 downloaded
51 CRM
[*********************100%***********************]  1 of 1 downloaded
52 SAP
[*********************100%***********************]  1 of 1 downloaded
53 TSM
[*********************100%***********************]  1 of 1 downloaded
54 TMO
[*********************100%***********************]  1 of 1 downloaded
55 TD
[*********************100%***********************]  1 of 1 downloaded
56 TOT
[*********************100%***********************]  1 of 1 downloaded
57 TM
[*********************100%***********************]  1 of 1 downloaded
58 UN
[*********************100%***********************]  1 of 1 downloaded
59 UL
[*********************100%***********************]  1 of 1 downloaded
60 UNP
[*********************100%***********************]  1 of 1 downloaded
61 UTX
[*********************100%***********************]  1 of 1 downloaded
62 UNH
[*********************100%***********************]  1 of 1 downloaded
63 VZ
[*********************100%***********************]  1 of 1 downloaded
64 V
[*********************100%***********************]  1 of 1 downloaded
65 WMT
[*********************100%***********************]  1 of 1 downloaded
66 DIS
[*********************100%***********************]  1 of 1 downloaded
67 WFC
[*********************100%***********************]  1 of 1 downloaded

In [3]:
quote = yf.download('AAPL', '2013-06-21', '2019-06-21')
    
# quote.columns = ['open', 'high', 'low', 'close', 'adjClose', 'volume']
# quote_dict = quote.to_dict()

[*********************100%***********************]  1 of 1 downloaded

In [5]:
quote

              Open    High     Low   Close  Adj Close     Volume
Date
2013-06-20   59.90   60.85   59.31   59.55      53.29   89327700
2013-06-21   59.78   60.00   58.30   59.07      52.86  120279600
2013-06-24   58.20   58.38   56.86   57.51      51.46  120186500
2013-06-25   57.96   58.26   56.98   57.52      51.47   78540700
2013-06-26   57.70   57.83   56.52   56.87      50.89   91931000
2013-06-27   57.04   57.34   56.22   56.25      50.34   84311500
2013-06-28   55.91   57.18   55.55   56.65      50.69  144629100
2013-07-01   57.53   58.90   57.32   58.46      52.31   97763400
2013-07-02   58.57   60.23   58.50   59.78      53.50  117466300
2013-07-03   60.12   60.43   59.64   60.11      53.79   60232200
2013-07-05   60.06   60.47   59.34   59.63      53.36   68506200
2013-07-08   60.02   60.14   58.66   59.29      53.06   74534600
2013-07-09   59.09   60.50   58.63   60.34      53.99   88146100
2013-07-10   59.94   60.69   59.75   60.10      53.78   70351400
2013-07-11   60.42   61.18   60.17   61.04      54.62   81573100
2013-07-12   61.09   61.40   60.49   60.93      54.52   69890800
2013-07-15   60.72   61.64   60.69   61.06      54.64   60479300
2013-07-16   60.93   61.53   60.60   61.46      54.99   54134500
2013-07-17   61.39   61.75   61.17   61.47      55.01   49747600
2013-07-18   61.91   62.12   61.52   61.68      55.19   54719700
2013-07-19   61.87   62.00   60.62   60.71      54.32   67180400
2013-07-22   61.35   61.39   60.78   60.90      54.50   51949100
2013-07-23   60.86   60.99   59.82   59.86      53.56   92348900
2013-07-24   62.70   63.51   62.18   62.93      56.31  147984200
2013-07-25   62.96   63.06   62.26   62.64      56.06   57373400
2013-07-26   62.19   63.01   62.05   63.00      56.37   50038100
2013-07-29   62.97   64.28   62.89   63.97      57.24   62014400
2013-07-30   64.28   65.31   64.18   64.76      57.95   77355600
2013-07-31   65.00   65.33   64.20   64.65      57.85   80739400
2013-08-01   65.11   65.26   64.75   65.24      58.38   51562700
...            ...     ...     ...     ...        ...        ...
2019-05-09  200.40  201.68  196.66  200.72     199.95   34908600
2019-05-10  197.42  198.85  192.77  197.18     197.18   41208700
2019-05-13  187.71  189.48  182.85  185.72     185.72   57430600
2019-05-14  186.41  189.70  185.41  188.66     188.66   36529700
2019-05-15  186.27  191.75  186.02  190.92     190.92   26544700
2019-05-16  189.91  192.47  188.84  190.08     190.08   33031400
2019-05-17  186.93  190.90  186.76  189.00     189.00   32879100
2019-05-20  183.52  184.35  180.28  183.09     183.09   38612300
2019-05-21  185.22  188.00  184.70  186.60     186.60   28364800
2019-05-22  184.66  185.71  182.55  182.78     182.78   29748600
2019-05-23  179.80  180.54  177.81  179.66     179.66   36529700
2019-05-24  180.20  182.14  178.62  178.97     178.97   23714700
2019-05-28  178.92  180.59  177.91  178.23     178.23   27948200
2019-05-29  176.42  179.35  176.00  177.38     177.38   28481200
2019-05-30  177.95  179.23  176.67  178.30     178.30   21218400
2019-05-31  176.23  177.99  174.99  175.07     175.07   27043600
2019-06-03  175.60  177.92  170.27  173.30     173.30   40396100
2019-06-04  175.44  179.83  174.52  179.64     179.64   30968000
2019-06-05  184.28  184.99  181.14  182.54     182.54   29773400
2019-06-06  183.08  185.47  182.15  185.22     185.22   22526300
2019-06-07  186.51  191.92  185.77  190.15     190.15   30684400
2019-06-10  191.81  195.37  191.62  192.58     192.58   26220900
2019-06-11  194.86  196.00  193.60  194.81     194.81   26932900
2019-06-12  193.95  195.97  193.39  194.19     194.19   18253200
2019-06-13  194.70  196.79  193.60  194.15     194.15   21674600
2019-06-14  191.55  193.59  190.30  192.74     192.74   18761500
2019-06-17  192.90  194.96  192.17  193.89     193.89   14669100
2019-06-18  196.05  200.29  195.21  198.45     198.45   26551000
2019-06-19  199.68  199.88  197.31  197.87     197.87   21124200
2019-06-20  200.37  200.61  198.03  199.46     199.46   21514000

[1511 rows x 6 columns]

In [25]:
quote.index = quote.index.strftime('%Y-%m-%d')

In [27]:
quote.index

Index(['2016-06-20', '2016-06-21', '2016-06-22', '2016-06-23', '2016-06-24',
       '2016-06-27', '2016-06-28', '2016-06-29', '2016-06-30', '2016-07-01',
       ...
       '2019-06-07', '2019-06-10', '2019-06-11', '2019-06-12', '2019-06-13',
       '2019-06-14', '2019-06-17', '2019-06-18', '2019-06-19', '2019-06-20'],
      dtype='object', length=756)